version: '2'
services:
  authelia:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./server:/usr/src/server
      - ./dist/server/src/public_html:/usr/src/server/src/public_html
      - ./client:/usr/src/client
      - ./shared:/usr/src/shared
      - ./config.minimal.yml:/etc/authelia/config.yml:ro
      - ./users_database.yml:/etc/authelia/users_database.yml
      - /tmp/authelia:/tmp/authelia
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on: 
      - redis
    networks:
      - example-network
    command:
      - "./node_modules/.bin/ts-node"
      - "-P"
      - "server/tsconfig.json"
      - "server/src/index.ts"
      - "/etc/authelia/config.yml"
