version: '2'
services:
  # Simulates client 1 - whitelisted by network rule.
  client-1:
    image: nginx:alpine
    volumes:
      - ./example/compose/nginx/clients/nginx.conf:/etc/nginx/nginx.conf
      - ./example/compose/nginx/clients/ssl:/etc/ssl
    ports:
      - "8081:443"
    networks:
      example-network:
        ipv4_address: 172.16.121.10
         

  # Simulates client 2 - not whitelisted by network rule.
  # This client must authenticate.
  client-2:
    image: nginx:alpine
    volumes:
      - ./example/compose/nginx/clients/nginx.conf:/etc/nginx/nginx.conf
      - ./example/compose/nginx/clients/ssl:/etc/ssl
    ports:
      - "8082:443"
    networks:
      example-network:
        ipv4_address: 172.16.121.11
