version: '2'
services:
  traefik-portal:
    image: traefik:v1.5.0-rc1-alpine
    command: --logLevel=DEBUG --web
    volumes:
      - ./example/traefik/portal/traefik.toml:/etc/traefik/traefik.toml
      - ./example/traefik/portal/ssl:/etc/ssl
    ports:
      - "8080:443"
    networks:
      - example-network
